apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.fullname" . }}-client
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "app-chart.client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-chart.client.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.client.service.port }}
        env:
{{- range $key, $value := .Values.client.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}
        # Secret references for sensitive data
        - name: VITE_OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            secretKeyRef:
              name: {{ include "app-chart.fullname" . }}-secrets
              key: otel-headers
