apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
spec:
  project: default
  source:
    chart: localstack
    repoURL: https://helm.localstack.cloud
    targetRevision: 0.4.1
    helm:
      valueFiles:
        - apps/localstack/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true