apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: dev-events
spec:
  project: default
  sources:
  - chart: localstack
    repoURL: https://helm.localstack.cloud
    targetRevision: 0.4.1
    helm:
      valueFiles:
      - $values/apps/localstack/values.yaml
  - repoURL: https://github.com/OrenAshkenazy/gitops
    targetRevision: appset
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
